// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPBgA1gqEMsvIkfOpshIOyUS9X3VSolpY',
    appId: '1:51982877472:web:7fcdb43c97aa278fcacd45',
    messagingSenderId: '51982877472',
    projectId: 'todo-bbab5',
    authDomain: 'todo-bbab5.firebaseapp.com',
    storageBucket: 'todo-bbab5.firebasestorage.app',
    measurementId: 'G-C8PHKW9RLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpCnazhESx0bAuGHXHOhnZAJcUd_8B-Iw',
    appId: '1:51982877472:android:967c7354c48a42f8cacd45',
    messagingSenderId: '51982877472',
    projectId: 'todo-bbab5',
    storageBucket: 'todo-bbab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSuYEPGA3aLEbIng19dZ7zx827_7PUoQ',
    appId: '1:51982877472:ios:dcd8262fd14ee047cacd45',
    messagingSenderId: '51982877472',
    projectId: 'todo-bbab5',
    storageBucket: 'todo-bbab5.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnSuYEPGA3aLEbIng19dZ7zx827_7PUoQ',
    appId: '1:51982877472:ios:dcd8262fd14ee047cacd45',
    messagingSenderId: '51982877472',
    projectId: 'todo-bbab5',
    storageBucket: 'todo-bbab5.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPBgA1gqEMsvIkfOpshIOyUS9X3VSolpY',
    appId: '1:51982877472:web:39649e9f5693a844cacd45',
    messagingSenderId: '51982877472',
    projectId: 'todo-bbab5',
    authDomain: 'todo-bbab5.firebaseapp.com',
    storageBucket: 'todo-bbab5.firebasestorage.app',
    measurementId: 'G-SB7WXYNMBD',
  );
}
